name: bs
channels:
  - defaults
  - conda-forge  
dependencies:
  - python=3.11.10
  - numpy
  - pandas
  - pip
  - pip:
    - omegaconf==2.3.0
    - docker==7.1.0
    - httpx==0.27.2
    - PyYAML==6.0.2
    - pybtex==0.24.0
    - synapseclient==4.7.0
    - git+https://github.com/yasinzaii/pybtex-apa7-style.git
    - brainles-preprocessing

